### ISSUE TITLE
How do I specify my Netlify access token from the cli?

### ISSUE THREAD

**Issue by steveharman** [jonahgoldwastaken/netlify-dyndns#2]
Hi,

I'm attempting to use `netlify-dyndns `from the command line on a Pi (not via Docker) but I can't see anything in the docs which explains how I specify my Netlify access token.

Can you help please?

Thanks

**Comment by jonahgoldwastaken** [comment]
You need to set it as an environment variable, the tool will pick it up automatically that way (either by `export NETLIFY_TOKEN={token}` or as a one-liner:`NETLIFY_TOKEN={token} netlify-dyndns`)

**Comment by steveharman** [comment]
Many thanks, it's working great now.
