### ISSUE TITLE
Multiple hosts being created - is this expected?

### ISSUE THREAD

**Issue by steveharman** [jonahgoldwastaken/netlify-dyndns#3]
Hi Jonah,

I'm now able to update Netlify's dns successfully, however each time I do - _another_ host is created in Netlify's DNS.  Is this expected?  

I thought  the idea was to create a record _if_ one was not already present, or update it [with an IP address] if the record already existed.   

![Domains___developer-ykt9rr4___Netlify](https://github.com/jonahgoldwastaken/netlify-dyndns/assets/12557929/6eaa79f8-a818-43af-9631-70c32a90cab8)

As you can see, I now have 2 x `pi `and 3 x `steve` entries in my domain.  The arguments I've been passing to `netlify-dns` are:

`netlify-dyndns --domain [mydomain] --hostname steve --ip-api=https://api.ipify.org --run-once`

Thanks,

**Comment by jonahgoldwastaken** [comment]
That's not supposed to happen. Please put the _full_ domain into the hostname parameter as specified in the README: `steve.mydomain.com`.
